OPENAI_API_KEY= "sk-proj-zpj6VStoSGNoEZKWMtEqT3BlbkFJXrkRbmkWA5yQpk7QxYje"

TIMESCALE_SERVICE_URL="postgres://tsdbadmin:lne10my8dt7b1rhv@eny2qgjth8.ax0en0061z.tsdb.cloud.timescale.com:37206/tsdb?sslmode=require"

ENABLE_LOAD=1